<?php 


// # Array LISTADO de Candidatos ---!
class NamesCandidates {

  protected $listNames = [

    "Juan Pérez",
    "María López",
    "Pedro Sánchez",
    "Ana García",
    "José Fernández",
    "Isabel González",
    "David Rodríguez",
    "Laura Gómez",
    "Miguel Torres",
    "Paula Martínez",
    "Luis Hernández",
    "Sara Díaz",
    "Antonio Jiménez",
    "Teresa Romero",
    "Francisco Moreno",
    "Carmen Castillo",
    "Alejandro Ruiz",
    "Amelia Blanco",
    "Daniel Sánchez",
    "Julia García",
    "Jorge Fernández",
    "Inmaculada González",
    "Rafael Torres",
    "Nuria Martínez",
    "Óscar Hernández",
    "Vanesa Díaz",
    "Aitor Jiménez",
    "Beatriz Romero",
    "Iván Moreno",
    "Laura Castillo",
    "Pablo Ruiz",
    "Clara Blanco",
    "Alejandro Sánchez",
    "Amelia García",
    "Daniel Fernández",
    "Julia González",
    "Jorge Torres",
    "Inmaculada Martínez",
    "Rafael Hernández",
    "Nuria Díaz",
    "Óscar Jiménez",
    "Vanesa Romero",
    "Aitor Moreno",
    "Beatriz Castillo",
    "Iván Ruiz",
    "Laura Blanco",
    "Pablo Sánchez",
    "Clara García",
    "Alejandro Fernández",
    "Amelia González",
    "Daniel Torres",
    "Julia Martínez",
    "Jorge Hernández",
    "Inmaculada Díaz",
    "Rafael Jiménez",
    "Nuria Romero",
    "Óscar Moreno",
    "Vanesa Castillo",
    "Aitor Ruiz",
    "Beatriz Blanco",
    "Iván Sánchez",
    "Laura García",
    "Pablo Fernández",
    "Clara González",
    "Alejandro Torres",
    "Amelia Martínez",
    "Daniel Hernández",
    "Julia Díaz",
    "Jorge Jiménez",
    "Inmaculada Romero",
    "Rafael Moreno",
    "Nuria Castillo",
    "Óscar Ruiz",
    "Vanesa Blanco",
    "Aitor Sánchez",
    "Beatriz García",
    "Iván Fernández",
    "Laura González",
    "Pablo Torres",
    "Clara Martínez",
    "Alejandro Hernández",
    "Amelia Díaz",
    "Daniel Jiménez",
    "Julia Romero",
    "Jorge Moreno",
    "Inmaculada Castillo",
    "Rafael Ruiz",
    "Nuria Blanco",
    "Óscar Sánchez",
    "Vanesa García",
    "Aitor Fernández",
    "Beatriz González",
    "Iván Torres",
    "Laura Martínez",
    "Pablo Hernández",
    "Clara Díaz",
    "Rosa Flores",
    "Manuel Castillo",
    "Julia García",
    "Daniel Sánchez",
    "Jorge Fernández",
    "Inmaculada González",
    "Rafael Torres",
    "Nuria Martínez",
    "Óscar Hernández",
    "Vanesa Díaz",

    "Lionel Messi",
    "Cristiano Ronaldo",
    "Neymar Jr.",
    "Robert Lewandowski",
    "Kylian Mbappé",
    "Mohamed Salah",
    "Kevin De Bruyne",
    "Harry Kane",
    "Robert Lewandowski",
    "Jadon Sancho",
    "Erling Haaland",
    "Riyad Mahrez",
    "Bruno Fernandes",
    "Antoine Griezmann",
    "Paul Pogba",
    "Sadio Mane",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",
    "Virgil van Dijk",
    "Trent Alexander-Arnold",
    "Kylian Mbappé",
    "Lautaro Martínez",
    "Harry Kane",
    "Raphael Varane",
    "Ruben Dias",

        
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Tom Hanks",
      "Johnny Depp",
      "Will Smith",
      "Matt Damon",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",
      "Ben Stiller",
      "Kevin Hart",
      "Will Ferrell",
      "Mark Wahlberg",
      "Jason Statham",
      "Denzel Washington",
      "Tom Cruise",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",
      "Ben Stiller",
      "Kevin Hart",
      "Will Ferrell",
      "Mark Wahlberg",
      "Jason Statham",
      "Denzel Washington",
      "Tom Cruise",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",
      "Ben Stiller",
      "Kevin Hart",
      "Will Ferrell",
      "Mark Wahlberg",
      "Jason Statham",
      "Denzel Washington",
      "Tom Cruise",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",
      "Ben Stiller",
      "Kevin Hart",
      "Will Ferrell",
      "Mark Wahlberg",
      "Jason Statham",
      "Denzel Washington",
      "Tom Cruise",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",
      "Ben Stiller",
      "Kevin Hart",
      "Will Ferrell",
      "Mark Wahlberg",
      "Jason Statham",
      "Denzel Washington",
      "Tom Cruise",
      "George Clooney",
      "Robert Downey Jr.",
      "Ben Affleck",
      "Dwayne Johnson",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Emma Watson",
      "Anne Hathaway",
      "Meryl Streep",
      "Julia Roberts",
      "Nicole Kidman",
      "Angelina Jolie",
      "Jennifer Aniston",
      "Reese Witherspoon",
      "Chris Hemsworth",
      "Chris Pratt",
      "Chris Evans",
      "Ryan Reynolds",
      "Bradley Cooper",


            "Billie Eilish",
    "Ariana Grande",
    "Olivia Rodrigo",
    "Taylor Swift",
    "BTS",
    "Ed Sheeran",
    "Dua Lipa",
    "The Weeknd",
    "Post Malone",
    "Justin Bieber",
    "Adele",
    "Coldplay",
    "Imagine Dragons",
    "The Chainsmokers",
    "Maroon 5",
    "Katy Perry",
    "Lady Gaga",
    "Demi Lovato",
    "Nicki Minaj",
    "Rihanna",
    "Selena Gomez",
    "Halsey",
    "Shawn Mendes",
    "Liam Payne",
    "Harry Styles",
    "Louis Tomlinson",
    "Niall Horan",
    "Zayn Malik",
    "J Balvin",
    "Ozuna",
    "Bad Bunny",
    "Anuel AA",
    "Daddy Yankee",
    "Maluma",
    "Jhay Cortez",
    "Sebastián Yatra",
    "Wisin",
    "Yandel",
    "Farruko",
    "CNCO",
    "Reik",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",
    "Carlos Vives",
    "Ricky Martin",
    "Pablo Alborán",
    "Alejandro Sanz",
    "Camila Cabello",
    "Gloria Trevi",
    "Fito Páez",
    "Diego Torres",
    "Natalia Lafourcade",
    "Zoé",
    "Mon Laferte",
    "Julieta Venegas",
    "Maná",
    "Luis Miguel",
    "Juanes",
    "Shakira",
    "Enrique Iglesias",


   ];

   

  public function getItems() {
      return $this->listNames;
  }
}


  //  $listNames = [
  //   "Lionel Messi",
  //   "Cristiano Ronaldo",
  //   "Neymar Jr.",
  //   "Robert Lewandowski",
  //   "Kylian Mbappé",
  //   "Mohamed Salah",
  //   "Kevin De Bruyne",
  //   "Harry Kane",
  //   "Robert Lewandowski",
  //   "Jadon Sancho",
  //   "Erling Haaland",
  //   "Riyad Mahrez",
  //   "Bruno Fernandes",
  //   "Antoine Griezmann",
  //   "Paul Pogba",
  //   "Sadio Mane",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",
  //   "Virgil van Dijk",
  //   "Trent Alexander-Arnold",
  //   "Kylian Mbappé",
  //   "Lautaro Martínez",
  //   "Harry Kane",
  //   "Raphael Varane",
  //   "Ruben Dias",

        
  //     "Leonardo DiCaprio",
  //     "Brad Pitt",
  //     "Tom Hanks",
  //     "Johnny Depp",
  //     "Will Smith",
  //     "Matt Damon",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",
  //     "Ben Stiller",
  //     "Kevin Hart",
  //     "Will Ferrell",
  //     "Mark Wahlberg",
  //     "Jason Statham",
  //     "Denzel Washington",
  //     "Tom Cruise",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",
  //     "Ben Stiller",
  //     "Kevin Hart",
  //     "Will Ferrell",
  //     "Mark Wahlberg",
  //     "Jason Statham",
  //     "Denzel Washington",
  //     "Tom Cruise",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",
  //     "Ben Stiller",
  //     "Kevin Hart",
  //     "Will Ferrell",
  //     "Mark Wahlberg",
  //     "Jason Statham",
  //     "Denzel Washington",
  //     "Tom Cruise",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",
  //     "Ben Stiller",
  //     "Kevin Hart",
  //     "Will Ferrell",
  //     "Mark Wahlberg",
  //     "Jason Statham",
  //     "Denzel Washington",
  //     "Tom Cruise",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",
  //     "Ben Stiller",
  //     "Kevin Hart",
  //     "Will Ferrell",
  //     "Mark Wahlberg",
  //     "Jason Statham",
  //     "Denzel Washington",
  //     "Tom Cruise",
  //     "George Clooney",
  //     "Robert Downey Jr.",
  //     "Ben Affleck",
  //     "Dwayne Johnson",
  //     "Scarlett Johansson",
  //     "Jennifer Lawrence",
  //     "Emma Watson",
  //     "Anne Hathaway",
  //     "Meryl Streep",
  //     "Julia Roberts",
  //     "Nicole Kidman",
  //     "Angelina Jolie",
  //     "Jennifer Aniston",
  //     "Reese Witherspoon",
  //     "Chris Hemsworth",
  //     "Chris Pratt",
  //     "Chris Evans",
  //     "Ryan Reynolds",
  //     "Bradley Cooper",


  //           "Billie Eilish",
  //   "Ariana Grande",
  //   "Olivia Rodrigo",
  //   "Taylor Swift",
  //   "BTS",
  //   "Ed Sheeran",
  //   "Dua Lipa",
  //   "The Weeknd",
  //   "Post Malone",
  //   "Justin Bieber",
  //   "Adele",
  //   "Coldplay",
  //   "Imagine Dragons",
  //   "The Chainsmokers",
  //   "Maroon 5",
  //   "Katy Perry",
  //   "Lady Gaga",
  //   "Demi Lovato",
  //   "Nicki Minaj",
  //   "Rihanna",
  //   "Selena Gomez",
  //   "Halsey",
  //   "Shawn Mendes",
  //   "Liam Payne",
  //   "Harry Styles",
  //   "Louis Tomlinson",
  //   "Niall Horan",
  //   "Zayn Malik",
  //   "J Balvin",
  //   "Ozuna",
  //   "Bad Bunny",
  //   "Anuel AA",
  //   "Daddy Yankee",
  //   "Maluma",
  //   "Jhay Cortez",
  //   "Sebastián Yatra",
  //   "Wisin",
  //   "Yandel",
  //   "Farruko",
  //   "CNCO",
  //   "Reik",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",
  //   "Carlos Vives",
  //   "Ricky Martin",
  //   "Pablo Alborán",
  //   "Alejandro Sanz",
  //   "Camila Cabello",
  //   "Gloria Trevi",
  //   "Fito Páez",
  //   "Diego Torres",
  //   "Natalia Lafourcade",
  //   "Zoé",
  //   "Mon Laferte",
  //   "Julieta Venegas",
  //   "Maná",
  //   "Luis Miguel",
  //   "Juanes",
  //   "Shakira",
  //   "Enrique Iglesias",


  //  ];

   

?>